# HTTP 服务器
http_server:
  host: "0.0.0.0"
  port: 8080

# pg
master_db:
  host: "localhost"
  port: 15432
  name: "wallet_services"
  user: "postgres"
  password: "a123456789"

# Redis
redis_config:
  addr: "127.0.0.1:16379"
  password: ""
  db: 0

# JWT
jwt_secret: "your-dev-secret-key"

# 闪兑聚合器
aggregator_config:
  wallet_account_addr: "127.0.0.1:8189"

  # wallet_chain_account 鉴权（预留）
  wallet_account_consumer_token: ""
  chain_consumer_tokens:
    "1": ""
  
  # 0x Protocol
  zerox_api_url: "https://api.0x.org"
  zerox_api_key: ""
  
  # 1inch
  oneinch_api_url: "https://api.1inch.dev"
  oneinch_api_key: ""
  
  # Jupiter
  jupiter_api_url: "https://quote-api.jup.ag"
  
  # LiFi
  lifi_api_url: "https://li.quest/v1"
  lifi_api_key: "272e3024-e7c5-44e9-b367-3169fec9fd5f.6665766b-00c0-4d02-a150-378d9a90ea2c"

  enable_providers:
    0x: false
    1inch: false
    jupiter: false
    lifi: true
